CREATE TABLE IF NOT EXISTS chat_reports (
  id bigint NOT NULL AUTO_INCREMENT,
  conversation_id bigint NOT NULL,
  reporter_id bigint NOT NULL,
  reported_user_id bigint NOT NULL,
  reason varchar(32) NOT NULL,
  description varchar(500) NOT NULL DEFAULT '',
  evidence_json longtext NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  handle_result varchar(500) NOT NULL DEFAULT '',
  handler_admin_id bigint NULL,
  handled_at datetime(3) NULL,
  created_at datetime(3) NULL,
  updated_at datetime(3) NULL,
  PRIMARY KEY (id),
  KEY idx_chat_reports_conversation_id (conversation_id),
  KEY idx_chat_reports_reporter_id (reporter_id),
  KEY idx_chat_reports_reported_user_id (reported_user_id),
  KEY idx_chat_reports_reason (reason),
  KEY idx_chat_reports_status (status),
  KEY idx_chat_reports_handler_admin_id (handler_admin_id),
  KEY idx_chat_reports_handled_at (handled_at),
  KEY idx_chat_reports_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
